"""Add Quiz and Attempt schema extensions

Revision ID: edffd81dbb0c
Revises: 94a223f2f46a
Create Date: 2026-07-20 11:08:18.290000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edffd81dbb0c'
down_revision: Union[str, None] = '94a223f2f46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempt_answers',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_answer', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempt_answers_attempt_id'), 'quiz_attempt_answers', ['attempt_id'], unique=False)
    op.create_index('ix_quiz_attempt_answers_question_id', 'quiz_attempt_answers', ['question_id'], unique=False)
    op.add_column('quiz_attempts', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('quiz_questions', sa.Column('lesson_id', sa.UUID(), nullable=True))
    op.add_column('quiz_questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('quiz_questions', sa.Column('difficulty', sa.String(), nullable=True))
    op.create_index(op.f('ix_quiz_questions_lesson_id'), 'quiz_questions', ['lesson_id'], unique=False)
    op.create_foreign_key(None, 'quiz_questions', 'lessons', ['lesson_id'], ['id'], ondelete='SET NULL')
    op.add_column('quizzes', sa.Column('chapter_id', sa.UUID(), nullable=True))
    op.add_column('quizzes', sa.Column('lesson_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_quizzes_course_id'), table_name='quizzes')
    op.create_index(op.f('ix_quizzes_course_id'), 'quizzes', ['course_id'], unique=False)
    op.create_index('ix_quizzes_chapter_id', 'quizzes', ['chapter_id'], unique=False)
    op.create_index('ix_quizzes_lesson_id', 'quizzes', ['lesson_id'], unique=False)
    op.create_foreign_key(None, 'quizzes', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quizzes', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_index('ix_quizzes_lesson_id', table_name='quizzes')
    op.drop_index('ix_quizzes_chapter_id', table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_course_id'), table_name='quizzes')
    op.create_index(op.f('ix_quizzes_course_id'), 'quizzes', ['course_id'], unique=True)
    op.drop_column('quizzes', 'lesson_id')
    op.drop_column('quizzes', 'chapter_id')
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.drop_index(op.f('ix_quiz_questions_lesson_id'), table_name='quiz_questions')
    op.drop_column('quiz_questions', 'difficulty')
    op.drop_column('quiz_questions', 'explanation')
    op.drop_column('quiz_questions', 'lesson_id')
    op.drop_column('quiz_attempts', 'duration')
    op.drop_column('quiz_attempts', 'percentage')
    op.drop_index('ix_quiz_attempt_answers_question_id', table_name='quiz_attempt_answers')
    op.drop_index(op.f('ix_quiz_attempt_answers_attempt_id'), table_name='quiz_attempt_answers')
    op.drop_table('quiz_attempt_answers')
    # ### end Alembic commands ###
